version: '3.7'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      # Copy over db create sql
      - ./data/sql/01_create.sql:/docker-entrypoint-initdb.d/01_create.sql
      # Copy over seed sql
      - ./data/sql/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql
